image: ruby:2.6.3

pipelines:
  default:
    - step:
        name: Generate the blog with Jekyll
        caches:
          - bundler
        script:
          - gem install bundler:2.0.1
          - bundle install --path vendor/bundle
          - bundle exec jekyll build --destination public
          - mkdir dist
          - tar -czvf dist/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C public .
        artifacts:
          - dist/**
    - step:
        name: Deploy to Web
        image: alpine
        deployment: production
        trigger: manual
        script:
          - tar -xf dist/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C upload
          - apk update && apk add lftp
          - lftp -c "set ssl:verify-certificate false; open ftp://francescogiavatto:tX5gFMAK5qsn@ftp.francescogiavatto.altervista.org; lcd ./upload; mirror --reverse --use-cache --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .svn"
#         - lftp -c "set ssl:verify-certificate false; open ftp://francescogiavatto:tX5gFMAK5qsn@ftp.francescogiavatto.altervista.org; lcd ./upload; mirror --reverse --delete --use-cache --verbose --allow-chown --allow-suid --no-umask --parallel=2 --exclude-glob .svn"
#          - apk update && apk add openssh rsync
#          - rsync -a  -e "ssh -o StrictHostKeyChecking=no" --delete upload/ francescogiavatto@ftp.francescogiavatto.altervista.org:/var/www/html-${BITBUCKET_BUILD_NUMBER}
#          - ssh -o StrictHostKeyChecking=no  francescogiavatto@ftp.francescogiavatto.altervista.org "rm -r /var/www/html"
#          - ssh -o StrictHostKeyChecking=no francescogiavatto@ftp.francescogiavatto.altervista.org"mv '/var/www/html-${BITBUCKET_BUILD_NUMBER}' '/var/www/html'"
definitions:
  caches:
    bundler: vendor/bundle